# Generated by Django 5.1 on 2024-11-14 10:01

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='project id')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('project_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='project URL')),
                ('members', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='member')),
                ('papers', models.ManyToManyField(to='papers.paper', verbose_name='paper')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
