# Generated by Django 5.1 on 2024-11-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_project_id',
            field=models.CharField(default=1, editable=False, max_length=8, verbose_name='project_id'),
            preserve_default=False,
        ),
    ]
