# Generated by Django 5.1 on 2024-11-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0002_project_short_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is_public'),
        ),
    ]
