# Generated by Django 5.1 on 2024-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0003_project_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='is_visible'),
        ),
    ]
