# Generated by Django 5.1 on 2024-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
        ('research_projects', '0004_project_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='papers',
            field=models.ManyToManyField(blank=True, null=True, to='papers.paper', verbose_name='paper'),
        ),
    ]
