# Generated by Django 5.1 on 2024-11-14 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0005_alter_project_papers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('posted_on', models.DateTimeField(auto_now_add=True, verbose_name='posted_on')),
                ('contributer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='contributer')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
