# Generated by Django 5.1 on 2024-11-14 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='research_projects.project', verbose_name='project'),
            preserve_default=False,
        ),
    ]
