# Generated by Django 5.1 on 2024-11-14 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
        ('research_projects', '0008_alter_post_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='papers',
        ),
        migrations.CreateModel(
            name='PapersCitationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_index', models.IntegerField(verbose_name='citation_index')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paper')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers_citation_indices', to='research_projects.project')),
            ],
            options={
                'db_table': 'papers_citation_indices',
                'constraints': [models.UniqueConstraint(fields=('citation_index', 'project'), name='unique_citation_index_project'), models.UniqueConstraint(fields=('paper', 'project'), name='unique_paper_project')],
            },
        ),
    ]
