# Generated by Django 5.1 on 2024-11-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0010_papersindices_delete_paperscitationindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersindices',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
