# Generated by Django 5.1 on 2024-11-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0011_papersindices_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_project_id',
            field=models.CharField(editable=False, max_length=8, unique=True, verbose_name='project_id'),
        ),
    ]
