# Generated by Django 5.1 on 2024-11-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='doi',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='doi'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='arxiv',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='arxiv_id'),
        ),
    ]
