# Generated by Django 5.1 on 2024-11-19 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_paper_paper_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='bookmark_user',
            field=models.ManyToManyField(related_name='bookmark_paper', to=settings.AUTH_USER_MODEL, verbose_name='bookmark_user'),
        ),
    ]
